#docker-compose --env-file ../.env up --build -d

services:
  app:
    container_name: app-service
    build:
      context: ..
      dockerfile: app-service/Dockerfile
    ports:
      - "1337:8080"
    environment:
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - DB_URL=jdbc:postgresql://db:5432/automatchic
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_LIFETIME=${JWT_LIFETIME}
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    container_name: postgres-db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: automatchic
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d automatchic" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: